movie_watchlist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('watchlist.urls')),
    path('', include('users.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views as user_views

app_name = 'users'

urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html',
                                                redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('account/', user_views.account, name='account'),

    # Password reset paths
    path('account/reset-password/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('account/reset-password/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('account/reset-password/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('account/reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

watchlist/urls.py
from django.urls import path
from . import views

app_name = 'watchlist'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('watchlists/', views.watchlists, name='watchlists'),
    path('watchlists/<watchlist>', views.watchlist_view, name='watchlist_view'),
    path('watchlists/movie/<int:movie_id>/delete/', views.delete_movie, name='delete_movie'),
    path('watchlists/<int:watchlist_id>/delete/', views.delete_watchlist, name='delete_watchlist'),
]

watchlist/models.py
from django.db import models
from django.contrib.auth.models import User


class WatchList(models.Model):
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE)
    watchlist_name = models.CharField(max_length=100)

    def __str__(self):
        return self.watchlist_name


class MovieData(models.Model):
    watchlist_name = models.ForeignKey(WatchList,
                                       on_delete=models.CASCADE)
    movie_title = models.CharField(max_length=250)
    movie_premiere_year = models.IntegerField('premiere year')
    movie_score = models.FloatField('score')
    movie_genres = models.CharField(max_length=250)

    def __str__(self):
        return self.movie_title

watchlist/views.py
import requests

from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django_tables2 import RequestConfig

from .tables import WatchlistTable
from .models import MovieData, WatchList
from movie_watchlist.secret_settings import api_key


def homepage(request):
    return render(request,
                  'watchlist/homepage.html')


@login_required
def watchlists(request):
    user_watchlists = WatchList.objects.filter(author=request.user)
    context = {
        'user_watchlists': user_watchlists,
    }
    if request.method == 'POST':
        new_watchlist_name = request.POST.get('new_watchlist_name')

        if WatchList.objects.filter(watchlist_name=new_watchlist_name, author=request.user).exists():
            messages.error(request, 'Watchlist with given name already exists.')
            return render(request,
                          'watchlist/homepage.html',
                          context)

        else:
            new_watchlist = WatchList(author=request.user, watchlist_name=new_watchlist_name)
            new_watchlist.save()
            return redirect('watchlist:watchlist_view', watchlist=new_watchlist_name)

    return render(request,
                  'watchlist/watchlists.html',
                  context)


@login_required
def watchlist_view(request, watchlist):
    current_watchlist = get_object_or_404(WatchList,
                                          watchlist_name=watchlist,
                                          author=request.user)
    watchlist_table = WatchlistTable(MovieData.objects.filter(watchlist_name=current_watchlist))
    RequestConfig(request).configure(watchlist_table)
    context = {
        'watchlist_table': watchlist_table,
        'watchlist': current_watchlist
    }
    if request.method == 'POST':
        searched_title = request.POST.get('movie_title')
        api_url = f'http://www.omdbapi.com/?apikey={api_key}&t={searched_title}'
        api_request = requests.get(api_url)

        json_data = api_request.json()

        if json_data.get('Error'):
            messages.error(request, 'Movie not found.')
            return render(request,
                          'watchlist/add_to_watchlist.html',
                          context)
        else:
            title = json_data['Title']
            score = float(json_data['imdbRating'])
            premiere_year = int(json_data['Year'][:4])
            genres = json_data['Genre']

            added_movie = MovieData(watchlist_name=current_watchlist,
                                    movie_title=title,
                                    movie_premiere_year=premiere_year,
                                    movie_score=score,
                                    movie_genres=genres)
            added_movie.save()

        return redirect('watchlist:watchlist_view', watchlist=added_movie.watchlist_name)

    return render(request,
                  'watchlist/add_to_watchlist.html',
                  context)


@login_required
def delete_movie(request, movie_id):
    movie = get_object_or_404(MovieData, pk=movie_id)

    if request.method == 'POST':
        movie.delete()
    return redirect('watchlist:watchlist_view', watchlist=movie.watchlist_name)


@login_required
def delete_watchlist(request, watchlist_id):
    watchlist = get_object_or_404(WatchList, pk=watchlist_id)

    if request.method == 'POST':
        watchlist.delete()
    return redirect('watchlist:watchlists')

watchlist/templates/watchlist/add_to_watchlist.html
{% extends 'templates/base.html' %}
{% load render_table from django_tables2 %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        Add something to watchlist: <br>
        <div class="input-group mb-3">
            <input class="form-control" name="movie_title" type="text" placeholder="Movie title...">
            <div class="input-group-append">
                <input class="btn btn-outline-danger" type="submit" value="Add">
            </div>
        </div>
    </form>
    {% render_table watchlist_table %}  
{% endblock %}

watchlist/templates/watchlist/homepage.html
{% extends 'templates/base.html' %}

{% block content %}
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-4">Movie watchlists</h1>
            <p class="lead">This site helps you create movie watchlists(who would have known?).</p>
        </div>
    </div>
{% endblock %}

watchlist/templates/watchlist/movie_delete_button.html
<form method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Delete" name="delete_movie"
           formaction="{% url 'watchlist:delete_movie' record.id %}">
</form>

watchlist/templates/watchlist/table_template.html
{% load django_tables2 %}
{% load i18n %}
{% block table-wrapper %}
<div class="table-container">
    {% block table %}
        <table {% render_attrs table.attrs class="table" %}>
            {% block table.thead %}
            {% if table.show_header %}
                <thead class="thead-default" {{ table.attrs.thead.as_html }}>
                <tr>
                {% for column in table.columns %}
                    <th {{ column.attrs.th.as_html }}>
                        {% if column.orderable %}
                            <a class="text-danger" href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a>
                        {% else %}
                            {{ column.header }}
                        {% endif %}
                    </th>
                {% endfor %}
                </tr>
                </thead>
            {% endif %}
            {% endblock table.thead %}
            {% block table.tbody %}
                <tbody {{ table.attrs.tbody.as_html }}>
                {% for row in table.paginated_rows %}
                    {% block table.tbody.row %}
                    <tr scope="row" {{ row.attrs.as_html }}>
                        {% for column, cell in row.items %}
                            <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
                        {% endfor %}
                    </tr>
                    {% endblock table.tbody.row %}
                {% empty %}
                    {% if table.empty_text %}
                    {% block table.tbody.empty_text %}
                        <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                    {% endblock table.tbody.empty_text %}
                    {% endif %}
                {% endfor %}
                </tbody>
            {% endblock table.tbody %}
            {% block table.tfoot %}
            {% if table.has_footer %}
            <tfoot {{ table.attrs.tfoot.as_html }}>
                <tr>
                {% for column in table.columns %}
                    <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
                {% endfor %}
                </tr>
            </tfoot>
            {% endif %}
            {% endblock table.tfoot %}
        </table>
    {% endblock table %}
{% endblock table-wrapper %}

watchlist/templates/watchlist/watchlists.html
{% extends 'templates/base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        Create your watchlist:
        <div class="input-group mb-3">
            <input class="form-control" name="new_watchlist_name" type="text" placeholder="Watchlist name...">
            <div class="input-group-append">
                <input class="btn btn-outline-danger" type="submit" value="Create">
            </div>
        </div>
    <p class="h4">Your Watchlists</p>
    <ul class="list-group list-group-flush">
        {% for watchlist in user_watchlists %}
            <li class="list-group-item">
                <a href="{% url 'watchlist:watchlist_view' watchlist %}" class="text-danger">{{ watchlist }}</a>
                    <input type="submit" value="Delete" class="btn btn-outline-danger float-right"
                           formaction="{% url 'watchlist:delete_watchlist' watchlist.id %}">
            </li>
        {% endfor %}
    </ul>
    </form>
{% endblock %}