movie_watchlist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('watchlist.urls')),
    path('', include('users.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views as user_views

app_name = 'users'

urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html',
                                                redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('account/', user_views.account, name='account'),

    # Password reset paths
    path('account/reset-password/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('account/reset-password/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('account/reset-password/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('account/reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

watchlist/urls.py
from django.urls import path
from . import views

app_name = 'watchlist'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('watchlists/', views.watchlists, name='watchlists'),
    path('watchlists/<watchlist>', views.watchlist_view, name='watchlist_view'),
    path('watchlists/movie/<int:movie_id>/delete/', views.delete_movie, name='delete_movie'),
    path('watchlists/<int:watchlist_id>/delete/', views.delete_watchlist, name='delete_watchlist'),
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-danger">
    <a class="navbar-brand" href="{% url 'watchlist:homepage' %}">Movie Watchlists</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        {% if user.is_authenticated %}
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'users:account' %}">Profile</a>

                <a class="nav-item nav-link" href="{% url 'watchlist:watchlists' %}">Watchlists</a>
            </div>
        {% endif %}
    </div>
    <div class="navbar-rigth">
        <div class="navbar-nav">
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'users:logout' %}">Logout</a>
            {% else %}
                <a class="nav item nav-link" href="{% url 'users:register' %}">Register</a>

                <a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
            {% endif %}
        </div>
    </div>
</nav>