movie_watchlist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('watchlist.urls')),
    path('', include('users.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views as user_views

app_name = 'users'

urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html',
                                                redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('account/', user_views.account, name='account'),

    # Password reset paths
    path('account/reset-password/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('account/reset-password/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('account/reset-password/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('account/reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)
    image = models.ImageField(default='default.png',
                              upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, **kwargs):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

users/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .functions import get_fav_genres


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account successfully created for {username}. You can now log in!')
            return redirect('users:login')
    else:
        form = UserRegisterForm()

    context = {'form': form}
    return render(request,
                  'users/register.html',
                  context)


@login_required
def account(request):
    fav_genres = get_fav_genres(request)
    if not fav_genres:
        fav_genres = ['Not enough movies in watchlists to tell your favourite genres.']
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST,
                                   instance=request.user)

        profile_form = ProfileUpdateForm(request.POST,
                                         request.FILES,
                                         instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Account updated!')
            return redirect('users:account')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'fav_genres': fav_genres
    }

    return render(request,
                  'users/account.html',
                  context)

users/templates/users/account.html
{% extends 'templates/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="modal-body row">

        <div class="col-md-6">
            <div class="media">
                <img class="rounded-circle account-img" src="{{ user.profile.image.url }}"
                            style="object-fit: cover" width="100px" height="100px">
                <div class="media-body">
                    <h2 class="account-heading">{{ user.username }}</h2>
                    <p class="text-secondary">{{ user.email }}</p>
                </div>
            </div>
            <h4>Favourite genres: </h4>
            <ul class="list-group list-group-flush">
                {% for genre in fav_genres %}
                <li class="list-group-item">{{ genre }}</li>
                {% endfor %}
            </ul>

        </div>

        <div class="col-md-6">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Edit Profile</legend>
                    {{ user_form|crispy }}
                    {{ profile_form|crispy }}
                </fieldset>
                <div class="form-group">
                    <input type="submit" value="Update" class="btn btn-outline-danger">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'templates/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log in!</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <input type="submit" value="Login" class="btn btn-outline-danger">
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account?<a class="ml-2 text-danger" href="{% url 'users:register' %}">Register now!</a>
            <br>
            <a class="ml-2 text-danger" href="{% url 'users:password_reset' %}">Forgot password?</a>
        </small>
    </div>
{% endblock %}

users/templates/users/logout.html
{% extends 'templates/base.html' %}
{% block content %}
    <h3>Logged out!</h3>
    <hr>
    <p>You have been logged out. You can <a href="{% url 'users:login' %}" class="text-danger">log in again.</a></p>
{% endblock %}

users/templates/users/register.html
{% extends 'templates/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Register</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <input type="submit" value="Register" class="btn btn-outline-danger">
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account?<a class="ml-2" style="color: red;" href="{% url 'users:login' %}">Log in!</a>
        </small>
    </div>
{% endblock %}